name: MBSN

pre_window: 
  - source /opt/ros/humble/setup.bash
  - source ../../ros2_ws//install/setup.bash

windows:
  - navstack:
      layout: tiled
      panes:
        - shell:
        #ROS2
        - bridge_unity:
          - ros2 run ros_tcp_endpoint default_server_endpoint
        - map_publisher:
          - ros2 run unity_sim map_publisher.py
        - rviz:
          - ros2 launch unity_sim rviz.launch.py